local lbl = lv_label_create("Hello LVGL")
lv_obj_set_pos(lbl, 10, 20)
lv_obj_set_size(lbl, 200, 40)
lv_obj_set_bg_color(lbl, 0xFF0000)
lv_obj_set_fg_color(lbl, 0xFFFFFF)
lv_obj_set_radius(lbl, 8)
lv_obj_set_border(lbl, 2, 0x00FF00)
lv_obj_set_padding(lbl, 5)
lv_obj_set_margin(lbl, 10)
lv_obj_set_opacity(lbl, 200)
lv_obj_set_visible(lbl, true)
lv_label_set_text(lbl, "Styled Label")
